# Generated by Django 4.1.7 on 2023-05-24 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaganKata',
            fields=[
                ('id_bagan', models.IntegerField(primary_key=True, serialize=False)),
                ('judul_bagan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BaganKumite',
            fields=[
                ('id_bagan', models.IntegerField(primary_key=True, serialize=False)),
                ('judul_bagan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.IntegerField(primary_key=True, serialize=False)),
                ('judul_event', models.CharField(max_length=50)),
                ('foto_event', models.ImageField(blank=True, null=True, upload_to='images/event/')),
                ('tanggal_tanding', models.DateTimeField()),
                ('tanggal_selesai', models.DateTimeField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.IntegerField(primary_key=True, serialize=False)),
                ('judul_kategori', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kelamin',
            fields=[
                ('id_kelamin', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_kelamin', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id_kelompok', models.IntegerField(primary_key=True, serialize=False)),
                ('judul_kelompok', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perguruan',
            fields=[
                ('id_perguruan', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_perguruan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tanding',
            fields=[
                ('id_tanding', models.IntegerField(primary_key=True, serialize=False)),
                ('judul_tanding', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utusan',
            fields=[
                ('id_utusan', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_utusan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Atlet',
            fields=[
                ('id_atlet', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_atlet', models.CharField(max_length=50)),
                ('id_kelamin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.kelamin')),
                ('id_perguruan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.perguruan')),
                ('id_utusan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.utusan')),
            ],
        ),
    ]
