# Generated by Django 4.1.7 on 2023-05-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id_event',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
