# Generated by Django 4.1.7 on 2023-05-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_id_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
