# Generated by Django 4.1.7 on 2023-08-05 16:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTatami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atlet',
            fields=[
                ('id_atlet', models.AutoField(primary_key=True, serialize=False)),
                ('nama_atlet', models.CharField(blank=True, max_length=50, null=True)),
                ('jenis_event', models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External')], max_length=10, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('putra', 'Putra'), ('putri', 'Putri')], max_length=10, null=True)),
                ('perguruan', models.CharField(blank=True, max_length=50, null=True)),
                ('perwakilan', models.CharField(blank=True, max_length=50, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('usia_atlet', models.IntegerField(blank=True, null=True)),
                ('berat_badan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bagan',
            fields=[
                ('id_bagan', models.AutoField(primary_key=True, serialize=False)),
                ('judul_bagan', models.CharField(max_length=100)),
                ('jenis_event', models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External')], max_length=10, null=True)),
                ('tanggal_tanding', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('S', 'Selesai'), ('P', 'Pending')], default='P', max_length=1)),
                ('kategori', models.CharField(blank=True, choices=[('kata', 'kata'), ('kumite', 'kumite')], max_length=6, null=True)),
                ('grup_kata', models.CharField(blank=True, choices=[('perorangan', 'Perorangan'), ('beregu', 'Beregu')], max_length=50, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('putra', 'Putra'), ('putri', 'Putri')], max_length=10, null=True)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tipe', models.CharField(blank=True, choices=[('ranking', 'Ranking')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BaganKategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('datetimekategori', models.DateTimeField(default=datetime.datetime.now)),
                ('judul_kategori', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('id_atlet', models.ManyToManyField(blank=True, to='bagan.atlet')),
            ],
        ),
        migrations.CreateModel(
            name='DetailBagann',
            fields=[
                ('id_detailbagan', models.AutoField(primary_key=True, serialize=False)),
                ('round', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True)),
                ('kata1', models.CharField(blank=True, max_length=50, null=True)),
                ('kata2', models.CharField(blank=True, max_length=50, null=True)),
                ('peserta1', models.BooleanField(default=False)),
                ('peserta2', models.BooleanField(default=False)),
                ('peserta1_telahdinilai', models.BooleanField(default=False)),
                ('peserta2_telahdinilai', models.BooleanField(default=False)),
                ('timer_status', models.BooleanField(default=False)),
                ('timer_reset', models.BooleanField(default=False)),
                ('grup', models.BooleanField(default=False)),
                ('penilaian', models.BooleanField(default=False)),
                ('dinilai', models.BooleanField(default=False)),
                ('tampilkan', models.BooleanField(default=False)),
                ('group_tanding', models.IntegerField(blank=True, null=True)),
                ('medali', models.BooleanField(default=False)),
                ('id_atlet', models.ManyToManyField(blank=True, to='bagan.atlet')),
            ],
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalScore',
            fields=[
                ('id_totalscore', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tatami',
            fields=[
                ('id_tatami', models.AutoField(primary_key=True, serialize=False)),
                ('tatami', models.CharField(max_length=50)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('penilaian', models.BooleanField(default=False)),
                ('admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bagan.admintatami')),
                ('id_jury', models.ManyToManyField(blank=True, to='bagan.jury')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreDetail',
            fields=[
                ('id_scoredetail', models.AutoField(primary_key=True, serialize=False)),
                ('jury_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('nama', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('tertinggi', models.BooleanField(blank=True, null=True)),
                ('terendah', models.BooleanField(blank=True, null=True)),
                ('id_jury', models.ManyToManyField(blank=True, to='bagan.jury')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id_score', models.AutoField(primary_key=True, serialize=False)),
                ('id_totalscore', models.ManyToManyField(blank=True, to='bagan.totalscore')),
                ('juri_score', models.ManyToManyField(blank=True, to='bagan.scoredetail')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('judul_event', models.CharField(max_length=50)),
                ('foto_event', models.ImageField(blank=True, null=True, upload_to='images/event/')),
                ('tanggal_tanding', models.DateTimeField()),
                ('tanggal_selesai', models.DateTimeField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('bagan_kategori', models.ManyToManyField(blank=True, to='bagan.bagankategori')),
                ('id_atlet', models.ManyToManyField(blank=True, to='bagan.atlet')),
                ('id_bagan', models.ManyToManyField(blank=True, to='bagan.bagan')),
                ('id_tatami', models.ManyToManyField(blank=True, to='bagan.tatami')),
            ],
        ),
        migrations.CreateModel(
            name='DetailMedali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('id_detailbagan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bagan.detailbagann')),
            ],
        ),
        migrations.AddField(
            model_name='detailbagann',
            name='id_score',
            field=models.ManyToManyField(blank=True, to='bagan.score'),
        ),
        migrations.AddField(
            model_name='detailbagann',
            name='id_scoredetail',
            field=models.ManyToManyField(blank=True, to='bagan.scoredetail'),
        ),
        migrations.AddField(
            model_name='detailbagann',
            name='id_tatami',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bagan.tatami'),
        ),
        migrations.CreateModel(
            name='DataItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField()),
                ('owner', models.CharField(max_length=255)),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bagan.statistic')),
            ],
        ),
        migrations.AddField(
            model_name='bagan',
            name='id_detailbagan',
            field=models.ManyToManyField(blank=True, to='bagan.detailbagann'),
        ),
        migrations.AddField(
            model_name='bagan',
            name='kategori_kata',
            field=models.ManyToManyField(blank=True, to='bagan.bagankategori'),
        ),
        migrations.AddField(
            model_name='atlet',
            name='id_score',
            field=models.ManyToManyField(blank=True, to='bagan.scoredetail'),
        ),
    ]
