# Generated by Django 4.1.7 on 2023-08-05 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmedali',
            name='id_atlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bagan.atlet'),
        ),
    ]
