# Generated by Django 4.1.7 on 2023-08-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0002_detailmedali_id_atlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailmedali',
            name='nama',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
