# Generated by Django 4.1.7 on 2023-08-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0003_detailmedali_nama'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbagann',
            name='biru',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailbagann',
            name='merah',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detailmedali',
            name='id_detailbagan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bagan.detailbagann'),
        ),
    ]
