# Generated by Django 4.1.7 on 2023-08-16 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0004_detailbagann_biru_detailbagann_merah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagan',
            name='tatami',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bagan.tatami'),
        ),
    ]
