# Generated by Django 4.1.7 on 2023-08-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0005_bagan_tatami'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atlet',
            name='berat_badan',
        ),
        migrations.RemoveField(
            model_name='atlet',
            name='tanggal_lahir',
        ),
        migrations.RemoveField(
            model_name='atlet',
            name='tempat_lahir',
        ),
    ]
