# Generated by Django 4.1.7 on 2023-08-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0007_remove_atlet_usia_atlet_atlet_nomor_tanding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagankategori',
            name='tipe',
            field=models.CharField(blank=True, choices=[('perorangan', 'Perorangan'), ('beregu', 'Beregu')], max_length=10, null=True),
        ),
    ]
