# Generated by Django 4.1.7 on 2023-08-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0008_bagankategori_tipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlet',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Putra', 'Putra'), ('Putri', 'Putri')], max_length=10, null=True),
        ),
    ]
