# Generated by Django 4.1.7 on 2023-08-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0009_alter_atlet_jenis_kelamin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlet',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('putra', 'Putra'), ('putri', 'Putri')], max_length=10, null=True),
        ),
    ]
