# Generated by Django 4.1.7 on 2023-09-10 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bagan', '0011_bagankategori_tatami_nomor_tanding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintatami',
            name='id_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
