# Generated by Django 4.1.7 on 2023-09-11 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0013_score_peserta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='peserta',
        ),
    ]
