# Generated by Django 4.1.7 on 2023-09-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0014_remove_score_peserta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbagann',
            name='perebutanjuara',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
