# Generated by Django 4.1.7 on 2023-12-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0016_bagan_banyaknya_juri'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbagann',
            name='bendera',
            field=models.BooleanField(default=False),
        ),
    ]
