# Generated by Django 4.1.7 on 2023-12-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0017_detailbagann_bendera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailbagann',
            name='bendera',
        ),
        migrations.AddField(
            model_name='bagan',
            name='bendera',
            field=models.BooleanField(default=False),
        ),
    ]
