# Generated by Django 4.1.7 on 2024-01-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0018_remove_detailbagann_bendera_bagan_bendera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailbagann',
            name='kata1',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detailbagann',
            name='kata2',
            field=models.CharField(blank=True, default='-', max_length=50, null=True),
        ),
    ]
