# Generated by Django 4.1.7 on 2024-01-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0019_alter_detailbagann_kata1_alter_detailbagann_kata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtletKumite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_atlet', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('subinfo', models.CharField(max_length=255)),
            ],
        ),
    ]
