# Generated by Django 4.1.7 on 2024-01-12 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0020_atletkumite'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolBaganKumite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('pool', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BaganKumiteDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penyisihan', models.IntegerField(default=1)),
                ('atlet1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atlet1', to='bagan.atletkumite')),
                ('atlet2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atlet2', to='bagan.atletkumite')),
                ('pool_bagan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bagan.poolbagankumite')),
            ],
        ),
    ]
