# Generated by Django 4.1.7 on 2024-01-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0021_poolbagankumite_bagankumitedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='atletkumite',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
