# Generated by Django 4.1.7 on 2024-01-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0022_atletkumite_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolbagankumite',
            name='pool',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
