# Generated by Django 4.1.7 on 2024-01-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0024_detailbagann_atlet1_detailbagann_atlet2_viewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagan',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
