# Generated by Django 4.1.7 on 2024-02-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bagan', '0025_bagan_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbagann',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detailbagann',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
