from django.urls import path
from .views import *
from . import views

urlpatterns = [
    path('', Home.as_view(), name="home"),
    path('kelevent/', kelEvent.as_view(), name="kelevent"),
    path('kelevent/<slug:slug>/', keldetailEvent.as_view(), name="keldetail"),
    path('kelevent/<slug:slug>/atlet/', keldetailAtlet.as_view(), name="keldetailatlet"),
    path('kelevent/<slug:slug>/atlet/<str:jenis_kelamin>/', keldetailAtlet.as_view(), name="kelatletjk"),
    path('kelevent/<slug:slug>/atlet/<int:atlet_pk>/edit/', AtletEdit.as_view(), name="atletedit"),
    path('kelevent/<slug:slug>/atlet/import/', importAtlet.as_view(), name="importatlet"),
    path('kelevent/<slug:slug>/tatami/', keldetailTatami.as_view(), name="keldetailtatami"),
    path('kelevent/<slug:slug>/tatami/<int:tatami_pk>/edit/', keldetailTatamiEdit.as_view(), name="keldetailtatamiedit"),
    path('kelevent/<slug:slug>/kata/', keldetailKata.as_view(), name="keldetailkata"),
    path('kelevent/<slug:slug>/kumite/', KumiteHome.as_view(), name="kumite-home"),
    path('kelevent/<slug:slug>/kumite/<int:bagan_pk>', BaganKumiteView.as_view(), name="bagan-kumite-view"),
    path('kelevent/<slug:slug>/kumite/controlpanel/', KumiteControlPanel.as_view(), name="kumite-cp"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/', keldetailKategori.as_view(), name="keldetailkategori"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/edit', BaganEdit.as_view(), name="bagan-edit"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/internal/', keldetailKategoriInternal.as_view(), name="keldetailkategoriinternal"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/external/', keldetailKategoriExternal.as_view(), name="keldetailkategoriexternal"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/internal/value', keldetailKategori.as_view(), name="valuebaganinternal"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/external/value', keldetailKategori.as_view(), name="valuebaganexternal"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:pk>/', keldetailBagan.as_view(), name="keldetailbagan"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:pk>/pdf/', GeneratePDF.as_view(), name="generatepdf"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/delete', views.deletebagan, name="deletebagan"),
    path('kelevent/<slug:event_slug>/kata/<int:tatami_pk>/jurypanel/1', JuryPanel1.as_view(), name="jurypanel1"),
    path('kelevent/<slug:event_slug>/kata/<int:tatami_pk>/jurypanel/2', JuryPanel2.as_view(), name="jurypanel2"),
    path('kelevent/<slug:event_slug>/kata/<int:tatami_pk>/jurypanel/send', views.jurysendscore, name="sendscore"),
    path('kelevent/<slug:event_slug>/kata/<int:tatami_pk>/jurypanel/sendbendera', views.jurysendbendera, name="sendbendera"),
    # path('kelevent/<slug:event_slug>/kata/<int:tatami_pk>/jurypanel/send_score', views.send_score_view, name="jurypanel1"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/detail', DetailBagan.as_view(), name="detailbagan"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/leave', LeaveControlPanel.as_view(), name="leavecontrolpanel"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/', controlPanel1.as_view(), name="controlpanel1"),
    # path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/ulang1/', views.PenilaianUlang1, name="nilai_ulang1"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/lihat/', LihatScore.as_view(), name="lihatscore1"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/mulai/1', MulaiPenilaian1.as_view(), name="mulaipenilaian1"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/mulai/2', MulaiPenilaian2.as_view(), name="mulaipenilaian2"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/total', views.totalnilai, name="totalnilai1"),
    # path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/test', views.test, name="test"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/scoringboard/', scoringBoard1.as_view(), name="scoringboard1"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/start_timer/', StartTimer1.as_view(), name='starttimer1'),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/timer_status/', TimerStatus1.as_view(), name='timerstatus1'),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/pause_timer/', PauseTimer1.as_view(), name='pausetimer1'),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/reset_timer/', ResetTimer1.as_view(), name='resettimer1'),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/reset_timer/1', ResetTimer2.as_view(), name='resettimer2'),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/tukar_warna/', TukarWarna1.as_view(), name='tukar1'),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/<int:bagan_pk>/<int:detailbagan_pk>/<int:tatami_pk>/tampilkan/', Tampilkan1.as_view(), name='tampilkan1'),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/tambah/', keltambahBagan.as_view(), name="keltambahbagan"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/tambah/internal/', keltambahBaganTest.as_view(), name="keltambahbaganinternal"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/tambah/external/', keltambahBaganTest.as_view(), name="keltambahbaganexternal"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/tambah/internal/medali/', TambahBaganMedali.as_view(), name="keltambahmedaliinternal"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/tambah/external/medali/', TambahBaganMedali.as_view(), name="keltambahmedaliexternal"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/tambah/internal/bendera/', TambahBaganBendera.as_view(), name="keltambahbenderainternal"),
    path('kelevent/<slug:event_slug>/kata/<slug:kategori_slug>/<str:jenis_kelamin>/tambah/internal/new/', TambahBaganNew.as_view(), name="keltambahbagannew"),
    # path('kelevent/<slug:event_slug>/kumite/')
    path('kelevent/<slug:event_slug>/kumite/createbagan', CreateBaganKumite.as_view(), name="cbkumite"),
    path('event/', listEvent.as_view(), name="listevent"),
    path('event/<slug:slug>/<str:jenis>', detailEvent.as_view(), name="detailevent"),
    path('event/<slug:slug>/<str:jenis>/<int:bagan_pk>', BaganView.as_view(), name="baganview"),
    # path('event/<slug:slug>/kumite', detailEvent.as_view(), name="detailevent"),
    path('login/', Login.as_view(), name="login"),
    path('logout/', Logout.as_view(), name='logout'),
    path('dummy/', dummy.as_view(), name='dummy'),
    path('main', Main.as_view(), name='main'),
    path('<slug>', Dashboard.as_view(), name='dashboard'),
    path('<slug>/chart', ChartData.as_view(), name='chart'),

]
